### ISSUE TITLE
Another typo error in IPS2GPIO_GeCoS_RGBW/module.php at line 325

### ISSUE THREAD

**Issue by dstrigl** [Joey-1970/SymconModules#3]
Line 325 in  IPS2GPIO_GeCoS_RGBW/module.php:

     $this->ToggleOutputPinStatusEx($Group, $Channel, , $FadeTime);

**Comment by Joey-1970** [comment]
...ist auch korrigiert, wobei die Fade-Funktion insgesamt noch "unvollendet" ist...
Bin da wegen der Integration des MCP23017 etwas im "Verzug" - sorry!

**Comment by dstrigl** [comment]
Danke! Ging auch mehr um den Fehler-Log im IP-Symcon.

**Comment by Joey-1970** [comment]
...bin trotzdem immer dankbar für diese Unterstützung! ;-)
